FROM golang:1.24-alpine

WORKDIR /app
COPY . .

RUN go mod tidy
RUN go build -o swift-api ./cmd

CMD ["sh", "-c", "go test ./... -v -p 1 -coverprofile=coverage.out | tee test-report.txt && go tool cover -html=coverage.out -o coverage.html"]
