version: '3.8'

services:
  db:
    image: postgres:17
    container_name: swift-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: swift
    ports:
      - "5432:5432"
    volumes:
      - swift-db-data:/var/lib/postgresql/data
      - ./scripts/init_schema.sql:/docker-entrypoint-initdb.d/init_schema.sql
    networks:
      - swift-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: swift-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_URL: postgres://user:pass@db:5432/swift?sslmode=disable
      SWIFT_CODES_FILE_PATH: /app/assets/swift_codes.csv
    networks:
      - swift-network

volumes:
  swift-db-data:

networks:
  swift-network:
